beego:
  orm_debug: true
  log_dir: ./target/logs

# 数据库连接信息配置
db:
  platform: mysql
  ip: 127.0.0.1
  port: 8090
  name: hellobeego
  username: root
  password: 123

# 权限验证相关的客户端 key
client:
  postman_client_key: 123

# 接口响应数据缓存（内存缓存）配置
response_cache:
  # 最大接口缓存数据条数
  max_entries: 1000
  # 缓存数据有效时间：两天
  expire_time_seconds: 43200

# 文件上传相关配置
attachment:
  # 单个文件的大小限制
  max_file_size_mb: 10
  # 文件名的字符个数限制（包括拓展名） - 和数据库字段保持一致
  max_file_name_length: 64
  # 支持的文件上传类型
  doc_support_type: [xls, xlsx, doc, pdf]
  pic_support_type: [png, jpg, jpeg]
  # 文件上传的存储目录（对于执行程序的相对目录）
  save_dir: ./target/upload/attachment
  doc_dir_name: doc
  pic_dir_name: pic
